// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6fhEo1DQ1AEjcigNFZB4c8nJDnXQiJY',
    appId: '1:341524060784:web:6816a0f14d18c16efbb2b5',
    messagingSenderId: '341524060784',
    projectId: 'msa2o-korah',
    authDomain: 'msa2o-korah.firebaseapp.com',
    storageBucket: 'msa2o-korah.appspot.com',
    measurementId: 'G-PF574X4VDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANTiYWGU76RIuD5roS-zj2WklAEXRPGvg',
    appId: '1:341524060784:android:a3cc983c8f9f0e31fbb2b5',
    messagingSenderId: '341524060784',
    projectId: 'msa2o-korah',
    storageBucket: 'msa2o-korah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrtffhDwu-2uDLtLVuwWsL-w0lzo0ZT1Q',
    appId: '1:341524060784:ios:485962acfe35169afbb2b5',
    messagingSenderId: '341524060784',
    projectId: 'msa2o-korah',
    storageBucket: 'msa2o-korah.appspot.com',
    iosBundleId: 'com.moace.msa2o.msa2oKorah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrtffhDwu-2uDLtLVuwWsL-w0lzo0ZT1Q',
    appId: '1:341524060784:ios:485962acfe35169afbb2b5',
    messagingSenderId: '341524060784',
    projectId: 'msa2o-korah',
    storageBucket: 'msa2o-korah.appspot.com',
    iosBundleId: 'com.moace.msa2o.msa2oKorah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs6fhEo1DQ1AEjcigNFZB4c8nJDnXQiJY',
    appId: '1:341524060784:web:223b73d0082b91cefbb2b5',
    messagingSenderId: '341524060784',
    projectId: 'msa2o-korah',
    authDomain: 'msa2o-korah.firebaseapp.com',
    storageBucket: 'msa2o-korah.appspot.com',
    measurementId: 'G-D7GES9P6BV',
  );
}
